### ISSUE TITLE
Connection seems to be broken

### ISSUE THREAD

**Issue by crowston** [jhschuster/homebridge-lacrosseweb#6]
The plugin was getting 301 errors trying to retrieve the status, and now stops Homebridge from launching. Is anyone else experiencing that? I'll see if I can get more detailed error messages.

**Comment by jhschuster** [comment]
I'm seeing this too. I suspect that LaCrosse has changed their web interface such that my scraping of it no longer works. I'll let you know what I find.

**Comment by crowston** [comment]
Thanks!

**Comment by sloopi** [comment]
I also experienced this.   
I am so running the beta version of LaCrosseAlerts iOS app.  At the same time I discovered the issue in Homebridge, I noticed the iOS app had updated.

**Comment by jhschuster** [comment]
They switched to using HTTPS and a self-signed certificate. So the connection is failing when connecting via HTTPS. But when I fix that (by ignoring HTTPS errors), I still am having a problem. The perl script I use to test is working fine. So it's something very under-the-hood w.r.t. the actual requests being made. I'm getting a success code from the POST I make when it logs in, but instead of getting JSON back I get "<div> Invalid or Expired URL.</div>".

**Comment by jhschuster** [comment]
Fixed. The change Lacrosse made was to prefer HTTPS over HTTP. This led to problems because they use a self-signed certificate and so I needed to disable SSL hostname checking by default. Also, the got module I use had problems with its prefixUrl option when used with HTTPS. Anyhow, it's working for me now. Update to 1.0.12.

**Comment by crowston** [comment]
I just updated and it's working again. Thanks!

**Comment by sloopi** [comment]
Works for me again too!  Thanks for your efforts!
